### ISSUE TITLE
Add kustomization.yaml

### ISSUE THREAD

**Issue by scottdhowell3** [thanos-io/kube-thanos#123]
I was wondering if I could add a kustomization.yaml that list the manifest files. kube-prometheus has one and would make it easier for teams using kustomization to just pull upstream changes into their kustomization when they are are building thanos.

**Comment by metalmatze** [comment]
Yep, that should work pretty like with kube-prometheus, I'm happy to accept a PR doing the same :blush:

**Comment by scottdhowell3** [comment]
#127 PR to add this

**Comment by metalmatze** [comment]
Closed with #127
