### ISSUE TITLE
all.jsonnet causes the store statefulset manifest to be duplicated

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [thanos-io/kube-thanos#149]
Currently the example jsonnet at `all.jsonnet` causes the StatefulSet for `thanos-store` to be duplicated, once with memcache and once without. This is probably due to https://github.com/thanos-io/kube-thanos/blob/a6a0027a3cd3da380479642debb202f2722710ee/all.jsonnet#L157 and this can be seen in https://github.com/thanos-io/kube-thanos/tree/a6a0027a3cd3da380479642debb202f2722710ee/examples/all/manifests

I suggest that the example be updated with a variable which takes in a boolean to check if memcached is required or not and updates the StatefulSet in-place. Let me know how that sounds and I can create a PR for the same.

**Comment by metalmatze** [comment]
The `all.jsonnet` example is an example that includes _all_ possible ways of setting up kube-thanos. It's not meant to be used. It's more or less only there to showcase how to use the various different jsonnet integrations we built.

**Comment by SayakMukhopadhyay** [comment]
Yeah, I understand that. I was still wondering if it could be improved or maybe a comment could be added with this info so that future users don't stumble on the same gotcha.

**Comment by stradigi-andres-de-castro** [comment]
> Yeah, I understand that. I was still wondering if it could be improved or maybe a comment could be added with this info so that future users don't stumble on the same gotcha.

Do it!
