### ISSUE TITLE
Thanos v0.17.0 and `--experimental.enable-index-cache-postings-compression`

### ISSUE THREAD

**Issue by craigfurman** [thanos-io/kube-thanos#174]
The flag `--experimental.enable-index-cache-postings-compression` was removed from [Thanos v0.17.0](https://github.com/thanos-io/thanos/releases/tag/v0.17.0), and its behaviour is now the default.

At the time of writing, kube-thanos sets this flag when an index cache is configured: https://github.com/thanos-io/kube-thanos/blob/master/jsonnet/kube-thanos/kube-thanos-store.libsonnet#L64. This is itself a little strange to me, because an in-memory index cache is used by default, even if it's not explicitly configured.

I'm new to this project and am not sure yet what the best way forward is. At the very least I think kube-thanos will have to pull the version from config and not set this flag when v0.17.0+ is used. That also avoids a breaking change.

I'm happy to PR this, but figured it'd be best to get maintainer opinions first.

**Comment by SuperQ** [comment]
This was fixed by https://github.com/thanos-io/kube-thanos/pull/180
