### ISSUE TITLE
Time based partitioning flags for the store

### ISSUE THREAD

**Issue by craigfurman** [thanos-io/kube-thanos#175]
It'd be neat if we could pass config elements that map to the `--max-time` and `--min-time` thanos store flags, to implement time-based partitioning (https://thanos.io/tip/components/store.md/#time-based-partitioning). At the moment, I'm doing this by patching the jsonnet-generated statefulset to append to the container's args.

I'm happy to make a PR, if this is a feature the maintainers want.

**Comment by metalmatze** [comment]
Glad to hear that the patching like that works for you, exactly why we want to use jsonnet.
I'm happy to get this into the project itself. Feel free to create a PR.

**Comment by craigfurman** [comment]
Thanks @metalmatze. I've had a go at it, let me know what you think if you find time to review it: https://github.com/thanos-io/kube-thanos/pull/187.

**Comment by craigfurman** [comment]
It looks like this was implemented in https://github.com/thanos-io/kube-thanos/pull/213.
