### ISSUE TITLE
Add convenience functions for Thanos Receive to demonstrate separate Ingester and Router functionality

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/kube-thanos#229]
Add convenience functions for Thanos Receive to demonstrate separate Ingester and Router functionality.

cc @yashrsharma44

**Comment by ianbillett** [comment]
I'll take this on :muscle:

**Comment by ianbillett** [comment]
Blocked on https://github.com/thanos-io/thanos/issues/4359

**Comment by yeya24** [comment]
Any progress @ianbillett? Would be nice to support this in kube-thanos

**Comment by ianbillett** [comment]
Thanks for poking @yeya24 - this issue had totally slipped my mind. No progress yet.

**Comment by ianbillett** [comment]
I'm starting to work on this now.

**Comment by ianbillett** [comment]
Still working on this.
