### ISSUE TITLE
"thanos-objectstorage" not found

### ISSUE THREAD

**Issue by liangyuanpeng** [thanos-io/kube-thanos#230]
1. kubectl apply -f manifests/  
2. kubectl describe po -n thanos thanos-store-0  

Just got error: `Error: secret "thanos-objectstorage" not found`  and i checked yaml files,have not found file of secret yaml.  

```shell
# ls manifests/
thanos-query-deployment.yaml      thanos-query-serviceMonitor.yaml  thanos-store-serviceAccount.yaml  thanos-store-service.yaml
thanos-query-serviceAccount.yaml  thanos-query-service.yaml         thanos-store-serviceMonitor.yaml  thanos-store-statefulSet.yaml
```

**Comment by liangyuanpeng** [comment]
Same problem in `examples/all/manifests/`

**Comment by yeya24** [comment]
Please check https://github.com/thanos-io/kube-thanos/tree/main/examples/development-minio directory.
