### ISSUE TITLE
Bad links in all.jsonnet

### ISSUE THREAD

**Issue by aletessier** [thanos-io/kube-thanos#242]
Links in example are broken. For example here:

https://github.com/thanos-io/kube-thanos/blob/add27c34e14b905f6fb9df9f0d48a8aa97923341/all.jsonnet#L113

should be https://thanos.io/tip/thanos/service-discovery.md/#dns-service-discovery

**Comment by kakkoyun** [comment]
Thanks for reporting :) Feel free to contribute :hugs:

**Comment by yeya24** [comment]
Closed by #250
