### ISSUE TITLE
Compact statefulset has a non-headless service as it's serviceName

### ISSUE THREAD

**Issue by stevehipwell** [thanos-io/kube-thanos#243]
I'm not sure if this is a problem, but the compact statefulset doesn't have the corresponding headless service to the value set in [serviceName](https://github.com/thanos-io/kube-thanos/blob/add27c34e14b905f6fb9df9f0d48a8aa97923341/jsonnet/kube-thanos/kube-thanos-compact.libsonnet#L130) like the other statefulsets.

**Comment by yeya24** [comment]
It makes sense. Are you willing to open a pr to fix it? Thanks!

**Comment by stevehipwell** [comment]
@yeya24 I'll have a go, I'm not really a jsonnet expert and I was working from the example manifests to create a [Thanos Helm chart](https://artifacthub.io/packages/helm/stevehipwell/thanos) when I spotted this.

**Comment by stevehipwell** [comment]
@yeya24 does compact need a non-headless service as there should only ever be one pod?

**Comment by yeya24** [comment]
> @yeya24 does compact need a non-headless service as there should only ever be one pod?

Good point! Then non-headless service seems ok in this case.
