### ISSUE TITLE
add extraEnv to all containers to make injection of custom env vars easier

### ISSUE THREAD

**Issue by mwasilew2** [thanos-io/kube-thanos#246]
I need to inject some environment variables to all Thanos pods (to configure tracing). Considering this is currently not supported by the lib I'll be probably doing this by patching multiple components in the generated json.

Would adding support for it be something you'd be interested in? I'm happy to prepare a PR

For example, for kube-thanos-store it could be something like:
```
(...)
      env: [
        (existing env config)
      ] + (
        if std.length(ts.config.extraEnv) > 0 then [
         ts.config.extraEnv,
        ] else []
      ),

(...)
```

not sure who the maintainers are, pinging  @yeya24 @brancz @metalmatze for some feedback

**Comment by mwasilew2** [comment]
Just realized that tracing in Thanos is configured via cli flags, not via env vars (e.g. https://github.com/jaegertracing/jaeger-client-go#environment-variables ) . I won't need this to move on with my config change, but if others find it useful I can still create a PR. Otherwise the issue can be closed.

**Comment by yeya24** [comment]
SGTM @mwasilew2!
