### ISSUE TITLE
questions: add secret for receiver  object bucket 

### ISSUE THREAD

**Issue by yangvipguang** [thanos-io/kube-thanos#259]
I want to know, Should i manually first add  a secret of object bucket  for receiver . 
![image](https://user-images.githubusercontent.com/11416887/147197724-394d6adb-3eee-4dc3-b909-7cedb0d0d0df.png)

**Comment by clyang82** [comment]
Yes. that is prerequisite. the object store can be consumed by receiver/store etc. refer to https://thanos.io/tip/thanos/storage.md/ for more details.
