### ISSUE TITLE
Can't get notifications from GitHub App

### ISSUE THREAD

**Issue by jobinjosem1** [thanos-io/kube-thanos#283]
Can we have GitHub App installed for this repo to get slack notifications for releases?

Currently, if I try to setup notifications using /github subscribe thanos-io/kube-thanos, I get the error to install the app.
![image](https://user-images.githubusercontent.com/55230905/183905668-c0449985-0575-4f8a-a901-10c2aff45bc0.png)

**Comment by metalmatze** [comment]
That won't be possible. 
Instead you can watch the repository on GitHub and subscribe to releases for example.
