### ISSUE TITLE
Eliminate job regex matcher on Alerts 

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/kube-thanos#60]
Although  I'm the one who introduced those, I realized they are error-prone and they could do more harm then they make things easier. Better to remove those selectors for more reliable alerting rules.

**Comment by metalmatze** [comment]
Yes, totally fine with that.
We should still keep in mind that we might have multiple receive statefulsets.

**Comment by kakkoyun** [comment]
Since `thanos-mixin` moved out to main `thanos` repo, closing this one.
