### ISSUE TITLE
[Question/Proposal] How to track compatible Thanos

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/kube-thanos#66]
Is it a good practice to create matching version tags with Thanos itself? And cut releases accordingly?

There might be several versions out there and depending on the version Thanos uses different flags, for example. It would be really good to know which versions are compatible with the current state.

What do you think?

**Comment by metalmatze** [comment]
Yes. That makes sense. Generally, whatever is on master is compatible with the latest Thanos release. But it might be good to start that with the next release. At least have branches for those.

**Comment by kakkoyun** [comment]
https://github.com/thanos-io/kube-thanos/releases/tag/v0.9.0
