### ISSUE TITLE
support jaeger tracing

### ISSUE THREAD

**Issue by yeya24** [thanos-io/kube-thanos#82]
It is convenient to add basic tracing configuration to the jsonnet files. I am not sure if this is in the scope of this repo?

**Comment by kakkoyun** [comment]
If we want to go down to that we should provide modules for all supported tracing backends (https://thanos.io/tracing.md/). So that end-user can choose and compose those to their setup.

**Comment by metalmatze** [comment]
We do have this in our downstream stack in [observatorium/configuration/](https://github.com/observatorium/configuration/).
I'm fine with cleaning these things up and moving them in here. Ours are for jaeger. 

If someone wants another supported tracing tool, they need to contribute this themselves.

**Comment by yeya24** [comment]
@metalmatze  Thanks! This repo really helps. I am using Jaeger as well.

**Comment by yeya24** [comment]
Close this one.
