### ISSUE TITLE
kube-thanos + istio = broken GRPC

### ISSUE THREAD

**Issue by Kampe** [thanos-io/kube-thanos#85]
Hey!  So I have istio installed in my cluster and am attempting to install Thanos components as well.  With istio installed, none of my grpc connections are successful and querier receives the following for all services:

`rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure"`

I've renamed the `grpc` service ports to `http2` to no avail, I'm utilizing the dnssrv+ approach for local service discovery `--store=dnssrv+_grpc._tcp.thanos-store.monitoring.svc.cluster.local`
(`--store=dnssrv+_http2._tcp.thanos-store.monitoring.svc.cluster.local`) with the name swap

Istio mutual TLS is disabled and istio-proxy logs don't give me any clues, however without istio, everything can discover one another fine, and works as intended.

Any ideas?

**Comment by Kampe** [comment]
Able to get it working by not allowing istio to intercept the comms on each StatefulSet, not ideal but this is a limitation of istio and StatefulSets at the moment (istio 1.4 and below)
```
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "10901"
        traffic.sidecar.istio.io/excludeInboundPorts: "10901"```

**Comment by metalmatze** [comment]
Seems to be very Istio specific, not sure how to help with our project itself. 
Do you think your issue is resolved and we can close this?

**Comment by Kampe** [comment]
It is indeed istio specific, I'll close for you :)

**Comment by Eslamanwar** [comment]
@Kampe If you can help ,this annotation is added to promethues-server statefulset ?

**Comment by jdfalk** [comment]
The other way around this is to set the grpc port name to https. I'm not sure why it thinks thanos' grpc isn't really grpc but for some reason it does and shuts it down immediately. 
See:
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by hairongGao** [comment]
> The other way around this is to set the grpc port name to https. I'm not sure why istio thinks thanos' grpc isn't really grpc but for some reason it does and shuts it down immediately.
> See:
> https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

Hi , 
Can you provide some more details about the workaround? I've been stuck on this for weeks. Much appreciated !

**Comment by itstaby** [comment]
I solved the problem by adding `appProtocol: tcp` to the grpc port entry for the services receiving the grpc requests (in my case these were headless services for thanos receive and storegateway). 

This is not documented anywhere but I followed a similar pattern documented for Loki: https://grafana.com/docs/loki/latest/setup/install/istio/

If you are using the thanos bitnami chart, it does not allow adding this to the service spec, so you will have to use something like kustomize.
