### ISSUE TITLE
side car service name is incorrect

### ISSUE THREAD

**Issue by omerlh** [thanos-io/kube-thanos#87]
The `sidecar.libsonnet` add a store with `prometheus-k8s.monitoring`, which is the regular Prometheus service, instead of pointing to `prometheus-operated.monitoring`, which is the headless service.

**Comment by metalmatze** [comment]
Right...
I think that's a bug indeed. In my personal setup I actually use the service you mention. We should update this in kube-thanos.
`--store=dnssrv+_grpc._tcp.prometheus-operated.monitoring.svc.cluster.local` :)

**Comment by omerlh** [comment]
I can open a PR...

**Comment by kakkoyun** [comment]
We have removed `sidecar` manifests from this repo. 
Check out https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-thanos-sidecar.libsonnet if it's still needed.

Or please open another issue with your justifications, if you still want to have the manifest for `sidecar`.
Thanks.
