### ISSUE TITLE
add envoy proxy for remote side car

### ISSUE THREAD

**Issue by omerlh** [thanos-io/kube-thanos#88]
see thanos-io/thanos#977

As Thanos Query does not support mTLS per store currently, the recommended pattern is to add for each remote store an envoy proxy, that can terminate the TLS connection. It will be nice to add it to kube-thanos, to make it easier to deploy it with Thanos.

**Comment by metalmatze** [comment]
I don't think we want to add this to kube-thanos itself. 
The beauty of jsonnet it, you can just enhance the jsonnet objects and add those sidecars in your setup.
I know that some people are working on adding TLS support into Thanos components directly, so hopefully we can have that for all components eventually.
